// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    partial class EducationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("dc18f43c-58a7-4d70-92cd-45689b306a95"),
                            Descripcion = "Curso de C# Basico",
                            FechaCreacion = new DateTime(2022, 7, 13, 8, 40, 11, 467, DateTimeKind.Local).AddTicks(5019),
                            FechaPublicacion = new DateTime(2024, 7, 13, 8, 40, 11, 467, DateTimeKind.Local).AddTicks(5026),
                            Precio = 56m,
                            Titulo = "C# desde cero hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("d0b81b60-fc7a-4134-82f5-de3c3cca52e4"),
                            Descripcion = "Curso de Java",
                            FechaCreacion = new DateTime(2022, 7, 13, 8, 40, 11, 467, DateTimeKind.Local).AddTicks(5054),
                            FechaPublicacion = new DateTime(2024, 7, 13, 8, 40, 11, 467, DateTimeKind.Local).AddTicks(5054),
                            Precio = 25m,
                            Titulo = "Master en Java Spring desde la raices"
                        },
                        new
                        {
                            CursoId = new Guid("b82d3154-768d-4017-8213-39f57602e23e"),
                            Descripcion = "Curso de Unit Test para Net Core",
                            FechaCreacion = new DateTime(2022, 7, 13, 8, 40, 11, 467, DateTimeKind.Local).AddTicks(5064),
                            FechaPublicacion = new DateTime(2024, 7, 13, 8, 40, 11, 467, DateTimeKind.Local).AddTicks(5064),
                            Precio = 1000m,
                            Titulo = "Master en Unit Test con CQRS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
